### ISSUE TITLE
Issue on syscalls::load_cell_data from ckb-std

### ISSUE THREAD

**Issue by XuJiandong** [ickb/v1-core#9]
The code below could be incorrect if the underlying data is larger than `data.len()`:
```Rust
    match load_cell_data(&mut data, 0, index, source) {
        Ok(DAO_DEPOSIT_DATA_SIZE) => data == DAO_DEPOSIT_DATA,
        _ => false,
    }
```
https://github.com/nervosnetwork/ckb-std/blob/36942aafbd6a8c380456256b3a565c0c624015f2/src/error.rs#L42-L46

It returns `LengthNotEnough`. If you want it to work in such a scenario, this error must be handled.

**Comment by phroi** [comment]
Hey @XuJiandong, thank you for publicly expressing your interest in iCKB by reviewing the L1 scripts source code, I personally appreciate a lot!! :pray:

As you can see, [this is the full function](https://github.com/ickb/v1-core/blob/d16333b95cda4d6bf0d2a15ca56f7c1cbeda9d50/scripts/contracts/ickb_logic/src/utils.rs#L51-L57):

```rust
pub fn is_deposit_cell(index: usize, source: Source) -> bool {
    let mut data = DAO_DEPOSIT_DATA.clone();
    match load_cell_data(&mut data, 0, index, source) {
        Ok(DAO_DEPOSIT_DATA_SIZE) => data == DAO_DEPOSIT_DATA,
        _ => false,
    }
}
```

The `is_deposit_cell` functionality is the following:
- returns `true` **if and only if** the cell data is exactly equal to that of a deposit.
- return `false` otherwise.

As per [NervosDAO RFC](https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0023-dao-deposit-withdraw/0023-dao-deposit-withdraw.md#deposit), the deposit data:

> MUST have [exactly] 8 bytes length cell data, filled with all zeros.

Don't trust me, [the RFC](https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0023-dao-deposit-withdraw/0023-dao-deposit-withdraw.md#deposit) or [the DAO code](https://github.com/nervosnetwork/ckb-system-scripts/blob/814eb82c44f560dbdad2be97eb85464062920237/c/dao.c#L499-L501), feel free to test it with a transaction :hugs:

Given this reasoning, by all means if the cell data is not exactly of **8**  bytes filled with all zeros, then is not a deposit and this function **must** return `false`. Say such a cell exists anyway as output, for example let's say 9 bytes length cell data, then the following happens:
-  [iCKB will not consider this cell as deposit, but as an unknown cell.](https://github.com/ickb/v1-core/blob/d16333b95cda4d6bf0d2a15ca56f7c1cbeda9d50/scripts/contracts/ickb_logic/src/celltype.rs#L104-L108)
- [Nervos DAO will not validate the transaction, due to this cell.](https://github.com/nervosnetwork/ckb-system-scripts/blob/814eb82c44f560dbdad2be97eb85464062920237/c/dao.c#L499-L501)

@XuJiandong does this sound reasonable?

**Comment by phroi** [comment]
PS: Additionally, always in the scenario of the **9** bytes DAO cell data, also the [iCKB Script will not validate](https://github.com/ickb/v1-core/blob/d16333b95cda4d6bf0d2a15ca56f7c1cbeda9d50/scripts/contracts/ickb_logic/src/celltype.rs#L78) as the this particular combination of scripts (iCKB Script as lock and Unknown as type) is a [misuse of the iCKB Script](https://github.com/ickb/v1-core/blob/d16333b95cda4d6bf0d2a15ca56f7c1cbeda9d50/scripts/contracts/ickb_logic/src/celltype.rs#L78).

**Comment by phroi** [comment]
Thank you again @XuJiandong for taking your time to understand and review the iCKB Scripts :pray:
